Repository libsemigroups/libsemigroups_pybind11, pull requests merged in 2024-04, with the labels that each got.

#147 Add tests for `Gabow`, `WordGraph` and `Paths`
  docs/source/api/digraph-helper.rst
  libsemigroups_pybind11/word_graph.py
  src/forest.cpp
  tests/test_gabow.py
  tests/test_paths.py
  tests/test_wordgraph.py
Labels: v1

#155 Add `Reporter` and `Runner`
  src/knuth-bendix.cpp
  src/main.cpp
Labels: v1

#159 ci: try to fix macosx
  .github/workflows/tests.yml
Labels: ci, v1

#160 Update the autodoc directive to improve overloaded functions
  Makefile
  docs/source/conf.py
  docs/source/data-structures/misc/reporter.rst
  docs/source/data-structures/misc/runner.rst
Labels: documentation, v1
